### ISSUE TITLE
files option not supported

### ISSUE THREAD

**Issue by apryor6** [matangover/mypy-vscode#1]
First off, this is great, and I see that this is a brand new project. Personally I'm very excited about it and spent the morning setting it up in my VS Code environment.

One of the first things I ran into was that if you don't open VS Code within the project that you want to analyze, then there is no autodetection of files that may be further down the tree (such as if your root directory is a monorepo). According to the mypy docs, it seems there is a `files` option that could be passed to provide additional locations to search, but when I provide this flag with a glob like "**/*.py" it fails with either a `mypy: can't read file...` (at the command line) or an error about a misunderstood option if placed in the mypy.ini in the [mypy] section.

Do you know if this is expected or if there is a workaround?

And, thanks -- half the reason I opened this issue was to have an excuse to encourage this project.

**Comment by matangover** [comment]
Thanks for your kind words! :)

I've also found that documentation about `files` and was confused as to why it wasn't working for me. Turns out that option isn't released yet -- it was merged to mypy master on [April 22](https://github.com/python/mypy/pull/6707) but the latest release 0.701 is from [April 16](https://pypi.org/project/mypy/#history).

You should set the `mypy.targets` setting in your workspace settings in VS Code -- here's what I wrote in the README:

> Use the `mypy.targets` setting to specify a list of target files or folders for mypy to analyze. By default the entire workspace folder is checked. Note that mypy does not recurse into folders without an __init__.py.


Mypy already has a [feature request](https://github.com/python/mypy/issues/6385) to recurse into all submodules even without __init__.py.

**Comment by matangover** [comment]
And I fixed the link in the README to point to the [stable](https://mypy.readthedocs.io/en/stable/config_file.html) rather than [latest](https://mypy.readthedocs.io/en/latest/config_file.html) mypy docs.

**Comment by matangover** [comment]
@apryor6 did this solve your issue?

**Comment by apryor6** [comment]
Yes thank you

**Comment by daturkel** [comment]
> I've also found that documentation about `files` and was confused as to why it wasn't working for me. Turns out that option isn't released yet -- it was merged to mypy master on [April 22](https://github.com/python/mypy/pull/6707) but the latest release 0.701 is from [April 16](https://pypi.org/project/mypy/#history).

this just cleared up so much confusion for me, thank you!
