### ISSUE TITLE
Upgrade mypy version and allow follow_imports = normal

### ISSUE THREAD

**Issue by seansnyder** [matangover/mypy-vscode#15]
Hello, would it be possible to upgrade the mypy version from .770 to the latest version (0.782), and change the mypyls code to allow follow_imports = normal in the config?

As of 0.780 dmypy now supports following imports. See note here:
https://mypy.readthedocs.io/en/stable/mypy_daemon.html#basic-usage

Right now there is code here that blocks follow_imports = normal:
https://github.com/matangover/mypyls/blob/master/mypyls/mypy_server.py#L109

Thank you very much!

**Comment by matangover** [comment]
Thanks! I've actually started working on this, but before pushing I was debating whether I should enable `follow_imports=normal` by default because it's still 'experimental' (but very useful in some cases). I was trying `follow_imports=normal` for about a week and it seems to be working fine. I did get a couple of internal mypy errors looking a bit like [this](https://github.com/python/mypy/issues/6935), which may or may not be related. Perhaps the smart choice is to keep using `skip` by default and let users override in `mypy.ini`.

**Comment by seansnyder** [comment]
I would probably vote for the default to align with the mypy default, which is now `normal` for both `dmypy` and `mypy`.

I'm assuming if the daemon crashes with one of those errors it will just start up again.

I don't feel strongly though as long as users can set it in `mypy.ini` so we can get our in-editor errors as close as possible to our command line / CI errors :)

**Comment by matangover** [comment]
I agree. Thanks for your input!

**Comment by matangover** [comment]
Finally done, sorry for the delay :)

**Comment by seansnyder** [comment]
Awesome, thank you!

**Comment by matangover** [comment]
Hey @seansnyder could you please help with a few minutes of your time by testing the beta version of the extension?
https://github.com/matangover/mypy-vscode/issues/27
