### ISSUE TITLE
How to force usage of the 'files' config item in the config file?

### ISSUE THREAD

**Issue by rkfillman** [matangover/mypy-vscode#23]
On the mypy command line, the way to get it to use the 'files' config item in the config file is to not pass any targets as parameters. Through this extension, I'm not sure how to do that. If I empty out the 'mypy.targets' setting in vscode, I see that it automatically adds the workspace root directory instead of reading from the mypy.ini config file

**Comment by matangover** [comment]
Unfortunately the extension doesn't support the files option in mypy.ini for now (along with some other options such as disable_error_codes). This is because of the way mypyls uses mypy as a library and is tricky to fix. But I'm working on a new version of the extension which uses dmypy directly and avoids this problem.

For now as a workaround I would suggest to just copy the value from mypy.ini to mypy.targets in the workspace configuration.

**Comment by rkfillman** [comment]
> But I'm working on a new version of the extension which uses dmypy directly and avoids this problem.
Awesome! Looking forward to it

> For now as a workaround I would suggest to just copy the value from mypy.ini to mypy.targets in the workspace configuration.
Yup, for now we just have the list in two places, which isn't ideal but works.

Thanks for the response!

**Comment by matangover** [comment]
Hey @rkfillman would you mind testing the new version of the extension? I would be happy for some feedback before I release the update.

**Comment by walleXD** [comment]
@matangover I'd happily take the new version for a spin. I use it day to day. Let me know. 

Thanks for the great work!

**Comment by matangover** [comment]
Thanks! I'll send it in the next few days.

**Comment by matangover** [comment]
Hi @walleXD, I posted the beta version [here](https://github.com/matangover/mypy-vscode/issues/27). Let me know if it works for you.
