### ISSUE TITLE
dmypy processes are not stopped when vscode is stopped

### ISSUE THREAD

**Issue by alehed** [matangover/mypy-vscode#47]
I don't know whether this is by design or by accident, but dmypy processes are not stopped when vscode is stopped.

This can become a problem when opening a workspace with mutliple python projects since each daemon can consume around 100 MB and closing vscode does not result in getting the memory back.

Looking at other plugins, it seems like the common thing to do is to spawn the processes as child processes of the extension.

**Comment by matangover** [comment]
Definitely not by design, I designed it so that dmypy is killed when VS Code exits. If it's not being killed it's a bug, can you give me steps to reproduce + versions of everything?

**Comment by matangover** [comment]
Thanks for the details! I have identified the regression, it was due to an internal change in VSCode which caused my daemon stopping code to stop working.

The daemon being launched as a child of pid 1 was not related to the problem. When you run e.g. `dmypy run` (which is what I'm doing in the extension), dmypy daemonizes itself on purpose. I then stop it manually with `dmypy stop` when the extension deactivates.

I could theoretically launch the daemon process in the foreground using the command `dmypy daemon` (which seems undocumented) but I prefer to leave it as is.

**Comment by alehed** [comment]
Thanks for following up. Is there a vscode bug report to track this?

**Comment by matangover** [comment]
There's no bug in VS Code, it's an internal change that affected my extension in a way I didn't expect. I have fixed the issue and will make a release soon

**Comment by alehed** [comment]
Ah, ok. Sorry, I misunderstood. Thanks!

**Comment by matangover** [comment]
I've released a new version which fixes the bug. If for any reason you still find dangling daemon processes please enable the `mypy.debugLogging` option and attach the log.

**Comment by alehed** [comment]
Awesome, thanks!
