### ISSUE TITLE
Missing required argument 'is_tty'

### ISSUE THREAD

**Issue by miroli** [matangover/mypy-vscode#7]
I recently started getting this error in VSCode, and I have no idea how I should debug further. To my knowledge I haven't changed my setup since the last time the extension worked a few days ago. I get this error message in the lower right corner of the editor.

```
Error running mypy: cmd_check() missing required argument 'is_tty' (pos 2)

Source: Mypy (Extension)
```

**Comment by matangover** [comment]
Thanks for report. This is due to a new version of mypy being released. The new version changed an internal API which this extension relies on. For now you can downgrade to the older version of mypy. 

I'm hoping to get some time soon to make the extension compatible with the newest version of mypy.

**Comment by matangover** [comment]
I fixed this in the latest version of mypyls. Please update to mypyls 0.2 using the instructions here:

https://github.com/matangover/mypy-vscode#updating
