### ISSUE TITLE
How do I get the extension to use the same venv as the vscode editor?

### ISSUE THREAD

**Issue by SimonShapiro** [matangover/mypy-vscode#9]
I can successfully run a program in the editor using a specified `command palete` set virtual environment which contains the imported library, but the mypy extension continues to report it as `cannot find module`.

**Comment by SimonShapiro** [comment]
After much trial and error, I found that if I included `ignore_missing_imports = True` in the `mypy.ini` file, the error message went away.

**Comment by matangover** [comment]
Hi Simon, I'm happy you managed to circumvent the error.

Just to clarify, the mypy extension does in fact use the venv configured globally in the Python extension. You can verify which venv is being used by looking in VS Code's Output pane, selecting 'mypy' in the dropdown, and looking for the following line:
```python_executable after applying config: /usr/local/bin/python3```
The interpreter path will indicate which venv the mypy extension is using.

If you still get `cannot find module`, probably it's because the module doesn't have type hints, see [mypy docs](https://mypy.readthedocs.io/en/latest/running_mypy.html#missing-imports). Using `ignore_missing_imports = True` in this case, as you did, is a viable way to silence the error.
